version: "3"

services:
  app:
    image: ghcr.io/manyfold3d/manyfold:latest
    ports:
      - 3214:3214
    volumes:
      - /path/to/your/libraries:/libraries
    environment:
      PUID: 1000 # The ID of the user the app will run as
      PGID: 1000 # The ID of the group the app will run as
      SECRET_KEY_BASE: a_nice_long_random_string
      REDIS_URL: redis://redis:6379/1

      # Database connection string; PostgreSQL is our recommended default
      DATABASE_URL: postgresql://manyfold:password@db/manyfold?pool=5
      # MySQL / MariaDB also works:
      # DATABASE_URL: mysql2://manyfold:password@db/manyfold?pool=5
      # You can also use SQLite if you don't want to run a separate database server.
      # Make sure the specified path is on a persistent volume!
      # DATABASE_URL: sqlite3:/config/manyfold.sqlite3?pool=5

      # Alternatively, you can set database connection parameters (host, username, etc)
      # in separate variables; see https://manyfold.app/sysadmin/configuration.html.

      # For details of other optional environment variables, including features such
      # as multiuser mode, visit https://manyfold.app/sysadmin/configuration.html
    depends_on:
      - db
      - redis
    networks:
      - manyfold
    links:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: manyfold
      POSTGRES_PASSWORD: password
    restart: on-failure
    networks:
      - manyfold

  redis:
    image: redis:7
    restart: on-failure
    networks:
      - manyfold

volumes:
  db_data:


networks:
  manyfold:
