local: &local
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 16) %>
  timeout: 5000

development:
  <<: *local
  database: db/development.sqlite3

test:
  <<: *local
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
