---
# This config file is for the i18n-js gem
# and provides translation into javascript
translations:
  - file: app/javascript/locales.json
    patterns:
      - "*.renderer.*"
      - "*.uploads.exceeds_max_size"
